### ISSUE TITLE
DictVectorizer.get_feature_names( ... ) should be DictVectorizer.get_feature_names_out( ...)

### ISSUE THREAD

**Issue by alitair** [cgpotts/cs224u#119]
I believe get_feature_names() is deprecated (and now removed).  get_feature_names_out() is the replacement.

**Comment by cgpotts** [comment]
Thank you! I will address this in the next update, after thorough testing against this new sklearn. (It seem we should also be freezing the version number for sklearn.)

**Comment by cgpotts** [comment]
This is now reflected in the Spring 2023 materials (which, though, are substantially different from the earlier ones in many ways).
