### ISSUE TITLE
Location of Yelp and Gigaword data files

### ISSUE THREAD

**Issue by michaelmccrae** [cgpotts/cs224u#145]
Where are the Gigaword and Yelp files located for vsm_01_distributional.ipynb notebook? 

![2024-03-11_22-57-08](https://github.com/cgpotts/cs224u/assets/23382819/76d79baf-6815-4eec-95b3-1a78c91e2c66)

**Comment by cgpotts** [comment]
This information is provided in the "Set-up" section higher up in the notebook.

**Comment by michaelmccrae** [comment]
See it now. My mistake. Thx. Note, the link is not secure due to lack of https, so you have to prompt it to start the download.
