### ISSUE TITLE
Problem loading video on Video: High-level goals and guiding hypotheses [slides] page

### ISSUE THREAD

**Issue by michaelmccrae** [cgpotts/cs224u#146]
The video at the following page is not loading. The page is also shooting a warning, since https is not implemented: [Video: High-level goals and guiding hypotheses](https://youtu.be/RiQgRJKqEhE) [[slides](https://web.stanford.edu/class/cs224u/slides/cs224u-vsm-part1-handout.pdf)] 

![2024-03-12_17-20-04](https://github.com/cgpotts/cs224u/assets/23382819/77ab142e-15ad-4654-9188-3ee79c582c36)

**Comment by cgpotts** [comment]
This issue is unrelated to this repo. I suggest reaching out to the SCPD people. The video linked is just on YouTube, but there may be an interaction with their portal.
