### ISSUE TITLE
YouTube videos for later lectures?

### ISSUE THREAD

**Issue by hammer** [cgpotts/cs224u#31]
Thank you for the wonderful course resources you've made available! Will the videos for the later lectures such as grounded language understanding, semantic parsing, evaluation metrics, and contextual word embeddings ever make their way to YouTube?

**Comment by cgpotts** [comment]
@hammer Thanks for the kind words, and my apologies for overlooking this for so long! All the videos are now up: 

https://www.youtube.com/playlist?list=PLoROMvodv4rObpMCir6rNNUlFAn56Js20

**Comment by rbhambriiit** [comment]
Thanks for sharing the video sessions from 2019. They are pure gold.

Can we expect an updated series in 2023 for the latest CS-224U syllabus?
