### ISSUE TITLE
data.zip, the data used in this course cannot be unpacked

### ISSUE THREAD

**Issue by Daijunxu** [cgpotts/cs224u#34]
I downloaded data.zip from "the course data" link on this notebook https://github.com/cgpotts/cs224u/blob/spring-2019/vsm_01_distributional.ipynb

System: 
macOS High Sierra 10.13.6
java 12.0.2 2019-07-16
Java(TM) SE Runtime Environment (build 12.0.2+10)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)

I run ` jar xvf data.zip` and get: 

  created: data/
 inflated: data/.DS_Store
  created: __MACOSX/
  created: __MACOSX/data/
 inflated: __MACOSX/data/._.DS_Store
  created: data/glove.6B/
 inflated: data/glove.6B/glove.6B.100d.txt
  created: __MACOSX/data/glove.6B/
 inflated: __MACOSX/data/glove.6B/._glove.6B.100d.txt
 inflated: data/glove.6B/glove.6B.200d.txt
 inflated: __MACOSX/data/glove.6B/._glove.6B.200d.txt
 inflated: data/glove.6B/glove.6B.300d.txt
 inflated: __MACOSX/data/glove.6B/._glove.6B.300d.txt
 inflated: data/glove.6B/glove.6B.50d.txt
 inflated: __MACOSX/data/glove.6B/._glove.6B.50d.txt
  created: data/negotiate/
 inflated: data/negotiate/data.txt
  created: __MACOSX/data/negotiate/
 inflated: __MACOSX/data/negotiate/._data.txt
 inflated: data/negotiate/selfplay.txt
 inflated: __MACOSX/data/negotiate/._selfplay.txt
 inflated: data/negotiate/test.txt
 inflated: __MACOSX/data/negotiate/._test.txt
 inflated: data/negotiate/train.txt
 inflated: __MACOSX/data/negotiate/._train.txt
 inflated: data/negotiate/val.txt
 inflated: __MACOSX/data/negotiate/._val.txt
 inflated: __MACOSX/data/._negotiate
  created: data/nlidata/
  created: data/nlidata/.ipynb_checkpoints/
 inflated: data/nlidata/.ipynb_checkpoints/prep_wordentail_data-checkpoint.ipynb
 inflated: data/nlidata/.ipynb_checkpoints/prep_wordentail_data-Copy1-checkpoint.ipynb
  created: data/nlidata/multinli_1.0/
extracted: data/nlidata/multinli_1.0/Icon
  created: __MACOSX/data/nlidata/
  created: __MACOSX/data/nlidata/multinli_1.0/
 inflated: __MACOSX/data/nlidata/multinli_1.0/._Icon
 inflated: data/nlidata/multinli_1.0/manuscript.pdf
 inflated: __MACOSX/data/nlidata/multinli_1.0/._manuscript.pdf
 inflated: data/nlidata/multinli_1.0/multinli_1.0_dev_matched.jsonl
 inflated: __MACOSX/data/nlidata/multinli_1.0/._multinli_1.0_dev_matched.jsonl
 inflated: data/nlidata/multinli_1.0/multinli_1.0_dev_matched.txt
 inflated: __MACOSX/data/nlidata/multinli_1.0/._multinli_1.0_dev_matched.txt
 inflated: data/nlidata/multinli_1.0/multinli_1.0_dev_mismatched.jsonl
 inflated: __MACOSX/data/nlidata/multinli_1.0/._multinli_1.0_dev_mismatched.jsonl
 inflated: data/nlidata/multinli_1.0/multinli_1.0_dev_mismatched.txt
 inflated: __MACOSX/data/nlidata/multinli_1.0/._multinli_1.0_dev_mismatched.txt
 inflated: data/nlidata/multinli_1.0/multinli_1.0_train.jsonl
 inflated: __MACOSX/data/nlidata/multinli_1.0/._multinli_1.0_train.jsonl
java.io.EOFException: Unexpected end of ZLIB input stream
	at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:245)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
	at java.base/java.util.zip.ZipInputStream.read(ZipInputStream.java:195)
	at java.base/java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:141)
	at jdk.jartool/sun.tools.jar.Main.extractFile(Main.java:1457)
	at jdk.jartool/sun.tools.jar.Main.extract(Main.java:1364)
	at jdk.jartool/sun.tools.jar.Main.run(Main.java:409)
	at jdk.jartool/sun.tools.jar.Main.main(Main.java:1681)

I run `unzip data.zip` and get:

Archive:  data.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of data.zip or
        data.zip.zip, and cannot find data.zip.ZIP, period.

**Comment by cgpotts** [comment]
My apologies. Please use 

http://web.stanford.edu/class/cs224u/data/data.tgz
