### ISSUE TITLE
Add environment variable check 

### ISSUE THREAD

**Issue by arun-ghontale** [cgpotts/cs224u#64]
The autograder being used in XCS224U when converting the notebook `hw_colors.ipynb` to a python script adds `get_ipython()` command to the script. This won't work unless you import it - `from IPython import get_ipython`. something like this:
![image](https://user-images.githubusercontent.com/31189279/90285341-58d1f380-de91-11ea-834d-8ee304fe22c0.png)

So it would be good to change these lines of code from:
 ![image](https://user-images.githubusercontent.com/31189279/90285038-b6197500-de90-11ea-8f3e-e8cf0370e401.png)
to this:
![image](https://user-images.githubusercontent.com/31189279/90285487-a64e6080-de91-11ea-8fff-0dc2d35f26d7.png)

I already have the permission to make changes to the repo. Just wanted to run by you once before making changes and committing it. Thanks @cgpotts

**Comment by cgpotts** [comment]
@arun-ghontale That change seems fine; free free to push changes! I'm glad to know that this is a potential issue too. Thanks!
