### ISSUE TITLE
hw_wordentail -define_graph() error

### ISSUE THREAD

**Issue by maerory** [cgpotts/cs224u#67]
While working on the hw_wordentail notebook, I have found an error in `test_TorchDeepNueralClassifier` function. 

The test aims to check whether the `nn.module` return value from `class TorchDeepNeuralClassifier` has been successfully implemented. However, the test function extracts the graph by using `define_graph()` function which is not implemented.

This should be changed to `build_graph()`. I can make the change and create a pull request if needed.

**Comment by cgpotts** [comment]
@maerory Thanks! I'll make the change now myself!
