### ISSUE TITLE
Consider using os.environ.get() instead of test ENV presence

### ISSUE THREAD

**Issue by qnu** [cgpotts/cs224u#68]
The code base thoroughly uses `in` idiom to test environment variable presence as a flag, like
```python
if 'IS_GRADESCOPE_ENV' not in os.environ:
    pass
```
To enable above condition, one has to `unset IS_GRADESCOPE_ENV`. Flipping the value has not effect, such as `IS_GRADESCOPE_ENV=0` or `IS_GRADESCOPE_ENV=1`.

However, it is usually to use `os.environ.get()` as a better alternative in production systems. For example,
```python
if not os.environ.get('IS_GRADESCOPE_ENV', False):
    pass

# or
if not os.environ.get('IS_GRADESCOPE_ENV', None):
    pass

# or strictly checking against pre-defined value
if not os.environ.get('IS_GRADESCOPE_ENV', '0') == '1':
    pass
```

Because in shell script, we usually test if an environment variable flag is _on_ by checking if it is present or if it is non-empty (i.e., `[[ ! -z "$VAR" ]]`). In this way, either of following will be evaluated as _false_ as expected and follows the convention, just in case users forgot to `unset` the value from the environment.
```shell
IS_GRADESCOPE_ENV=
unset IS_GRADESCOPE_ENV
export IS_GRADESCOPE_ENV=''
```

Just a minor issue, feel free to ignore. 😄

**Comment by cgpotts** [comment]
@qnu Sure! Do you separately have an environment variable `IS_GRADESCOPE_ENV` for some reason?

**Comment by qnu** [comment]
No really, but plan to 1) set this variable to make sure nothing breaks before submission and 2) not sure if I can use it as a flag to mock the grade or use my own grade code.

**Comment by cgpotts** [comment]
Thanks for this feedback @qnu! For now, I am going to leave these conditionals as-is, since a lot of grading infrastructure depends on it. The expectation is that `IS_GRADESCOPE_ENV` will not be in the user's environment at all, which seems reasonable.

**Comment by qnu** [comment]
Definitely, makes sense!
