### ISSUE TITLE
Typo in hw_wordentail.ipynb

### ISSUE THREAD

**Issue by votrubac** [cgpotts/cs224u#78]
> I wanted to create PR but I do not have create branch permission.

Minor thing, but could improve understanding. In hw_wordentail.ipynb:

"That is, if a word w appears in a training pair, it does not occur in any **text** pair. "

should read as:

"That is, if a word w appears in a training pair, it does not occur in any **test** pair. "

**Comment by insop** [comment]
Hi @votrubac 

If you can create a PR, what you can do is 
- fork the repo, and clone to your env
- create a branch from your local env, and make the change and push to your forked branch
- from there you can create a PR.
- 
This is a longer version of how to do it, in case https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by cgpotts** [comment]
@votrubac @insop Thanks for this! I appreciate the typo correction. I'll just make the change -- seems easier!
