### ISSUE TITLE
Should set return_dict=True for bert_model in finetuning.ipynb

### ISSUE THREAD

**Issue by wwwennn** [cgpotts/cs224u#82]
Hi there,

I noticed that [this line](https://github.com/cgpotts/cs224u/blob/master/finetuning.ipynb?short_path=482dd4f#L288) should be changed to
```
reps = bert_model(X_example, attention_mask=X_example_mask, return_dict=True)
```
for the following cells to work.

Thank you,
Wen

**Comment by cgpotts** [comment]
@wwwennn Thanks for the note! This isn't the behavior I see. Can you verify that you are using `transformers==4.3.3`?

**Comment by wwwennn** [comment]
You're right. I was running with transformers=3.4. Things work fine after switching to 4.3.3
